# Generated by Django 3.2.7 on 2021-09-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('-name',)},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ('-points',)},
        ),
        migrations.AddField(
            model_name='game',
            name='link',
            field=models.CharField(default='no link', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
