# Generated by Django 3.2.7 on 2021-09-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210917_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.CharField(default='https://i.pinimg.com/originals/73/0d/b4/730db4df9b783d47421fa0f53d8c4537.png', max_length=256),
            preserve_default=False,
        ),
    ]
